image: ruby:2.3

test:
  before_script:
    - bundle install --deployment
    - .circleci/install.sh
    - mkdir .circleci/tmp
    - bundle exec rake start
  script:
    - bundle exec rake test
    - bundle exec rake lint
  cache:
    key: "gemz"
    paths:
    - ./vendor
